### ISSUE TITLE
Unable to get two tabultor tables working on the same page

### ISSUE THREAD

**Issue by akrishnamo** [anvilistas/tabulator#150]
One tabulator table works fine, the other works fine. If i have them two on the same page, only the first gets displayed

`self.tabulator_1.data, self.tabulator_2.data=itemz , itemz2` displays itemz but not itemz2
![image](https://github.com/user-attachments/assets/4b365495-51fe-4355-aaa8-afeb8f261728)

`self.tabulator_1.data, self.tabulator_2.data=itemz2 , itemz` displays itemz2 but not itemz
![image](https://github.com/user-attachments/assets/9ae5d9cf-2152-4ee4-a502-99785049e2a4)

if i have only one table on the page , it works fine with either itemz or itemz2

Error
[An internal error has occurred] - see browser console for more details
TypeError: e.split is not a function
    at D.setField (https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:3:11420)
    at new D (https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:3:10007)
    at pi._addColumn (https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:14:132444)
    at https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:14:132305
    at Array.forEach (<anonymous>)
    at pi.setColumns (https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:14:132284)
    at _._initializeTable (https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:17:38015)
    at _._create (https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:17:36242)
    at https://cdn.skypack.dev/-/tabulator-tables@v5.4.4-mwII18KRUa4U2SLwD6wY/dist=es2020,mode=imports,min/optimized/tabulator-tables.js:17:34812

**Comment by s-cork** [comment]
Could you provide a minimal example clone link?

**Comment by akrishnamo** [comment]
[Clone Link](https://anvil.works/build#clone:CIHXUN6Q72NEXLGQ=ALJFCMQHZN6ZDLGGE2YKVIPG) 

Scenarios>Params Test>Output Summary

**Comment by s-cork** [comment]
I haven't tried yet but are there any reproduction steps I'll need to follow?

**Comment by akrishnamo** [comment]
If you navigate to Scenarios>Params Test>Output Summary, you can see the issue. It is in the form called output_summary_page

**Comment by s-cork** [comment]
You don't seem to be setting the columns
I would consider using auto_columns 
If i set auto_columns to True the the data appears as expected

**Comment by akrishnamo** [comment]
Auto Columns works! Thanks.  

Just a note - if you see my column definitions (col_defs) in the code, they have been commented out when I did all permutations. They don't work even if enabled.

Thanks again

**Comment by s-cork** [comment]
that's because the col definitions are wrong, try debugging the col definitions with print statements.
By using enumerate, you are setting the col title and field to a tuple e.g. `(0, 't')`
This is not a valid field.

**Comment by akrishnamo** [comment]
> that's because the col definitions are wrong, try debugging the col definitions with print statements. By using enumerate, you are setting the col title and field to a tuple e.g. `(0, 't')` This is not a valid field.

Apologies - just saw this--very idiotic of me. I wasted so much time on this, and yours as well
